// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/gol4ng/httpware/v4/auth"

	mock "github.com/stretchr/testify/mock"
)

// Authenticator is an autogenerated mock type for the Authenticator type
type Authenticator struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: _a0, _a1
func (_m *Authenticator) Authenticate(_a0 context.Context, _a1 auth.Credential) (auth.Credential, error) {
	ret := _m.Called(_a0, _a1)

	var r0 auth.Credential
	if rf, ok := ret.Get(0).(func(context.Context, auth.Credential) auth.Credential); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.Credential)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, auth.Credential) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
