// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RateLimiter is an autogenerated mock type for the RateLimiter type
type RateLimiter struct {
	mock.Mock
}

// Inc provides a mock function with given fields:
func (_m *RateLimiter) Inc() {
	_m.Called()
}

// IsLimitReached provides a mock function with given fields:
func (_m *RateLimiter) IsLimitReached() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Start provides a mock function with given fields:
func (_m *RateLimiter) Start() {
	_m.Called()
}

// Stop provides a mock function with given fields:
func (_m *RateLimiter) Stop() {
	_m.Called()
}
