// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// RateLimiter is an autogenerated mock type for the RateLimiter type
type RateLimiter struct {
	mock.Mock
}

// Allow provides a mock function with given fields: req
func (_m *RateLimiter) Allow(req *http.Request) error {
	ret := _m.Called(req)

	var r0 error
	if rf, ok := ret.Get(0).(func(*http.Request) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Dec provides a mock function with given fields: req
func (_m *RateLimiter) Dec(req *http.Request) {
	_m.Called(req)
}

// Inc provides a mock function with given fields: req
func (_m *RateLimiter) Inc(req *http.Request) {
	_m.Called(req)
}
