name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.20", "1.23", "1.24"]
        os: [ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go ${{ matrix.go }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Verify Go version
      run: go version

    - name: Install dependencies
      run: go mod tidy

    - name: Run Tests
      run: go test -race -coverprofile="coverage.out" -v ./...

    - uses: qltysh/qlty-action/coverage@v1
      with:
        oidc: true
        files: coverage.out
